[project]
name = "nanogpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Reza Mehr", email = "334387066+reza-mehr@users.noreply.github.com" }
]
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "tensorboard>=2.21.0",
    "torch>=2.8.0",
    "tqdm>=4.70.1",
    "tyro>=1.0.16",
]

[project.scripts]
nanogpt = "nanogpt:main"

[dependency-groups]
dev = [
    "ipykernel>=6.31.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
